### ISSUE TITLE
mpdf pfad

### ISSUE THREAD

**Issue by withanage** [kadowa/xml2pdf-php#1]
@kadowa
habe die mpdf binär-dateien aus dem projekt rausgeschmissen und  als sub-module eingebunden.
Kannst du hier das Pfad konfugierer-bar machen oder holen wird das Skript auch  ins mpt ?
https://github.com/kadowa/xml2pdf-php/blob/master/mpdf.php#L8

**Comment by kadowa** [comment]
Nutzt ihr mpdf denn noch? Ich dachte, das wäre längst vom Tisch, weil man keine Fußnoten damit formatieren kann?

Ich würde vorschlagen, das Skript ins MPT zu integrieren, wenn ihr es weiter verwenden wollt.

**Comment by withanage** [comment]
ja, eigentlich will ich die option  mpdf für andere immer offen lasssen. Denke macht sinn ins mpt zu intergrieren. 
Ich mache für eigenständige Skripte so eine  MIT Lizens Skript mit mein Name , da es ohne Prjekt verwendet werden kann.  Soll ich es auch den header mit dein name einfügen ?
https://github.com/withanage/mpt/blob/master/static/tools/postProcess.py

**Comment by kadowa** [comment]
Gerne, ja.
